### ISSUE TITLE
raygui support

### ISSUE THREAD

**Issue by buckle2000** [deltaphc/raylib-rs#7]
Hi @deltaphc , have you considered supporting [raygui](https://github.com/raysan5/raygui)?

[I have created bindings of most functions](https://github.com/buckle2000/raygui/)

These are left unimplemented.

```
// TODO please write those for me
// GuiTextBox|bounds: Rectangle, text: *mut ::std::os::raw::c_char, textSize: i32, editMode: bool|bool
// GuiTextBoxMulti|bounds: Rectangle, text: *mut ::std::os::raw::c_char, textSize: i32, editMode: bool|bool
// GuiListViewEx|bounds: Rectangle, text: *mut *mut ::std::os::raw::c_char, count: i32, enabled: *mut i32, active: *mut i32, focus: *mut i32, scrollIndex: *mut i32, editMode: bool|bool
// GuiLoadStyleProps|props: *const i32, count: i32|
```

**Comment by deltaphc** [comment]
Supporting more of the "raylib ecosystem" certainly seems worth doing. Extra things like these would probably be behind Cargo feature flags since not everyone would need raygui.

That said, I think I'll look at this more closely after 0.10.0 of raylib-rs is published. I'm thinking it'll be lumped in with other major changes for 0.11.0 (tentatively).

**Comment by Dacode45** [comment]
Raygui is now in on master. See the rgui sample.

**Comment by BenTearzz** [comment]
Is Raygui going to be updated to the latest 2.6 version?

**Comment by yummydev** [comment]
No plans for incremental updates for raygui. It changes too often. It's a single header library so feel free to fork raylib-sys and update.
